# 1. Light Data

In [26]:
#!/usr/bin/env python

# make sure to install these packages before running:
%pip install pandas
%pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("www.dallasopendata.com", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(www.dallasopendata.com,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
# results = client.get("d7e7-envw", limit=10000)
results = client.get(
    "d7e7-envw",
    where="service_request_type LIKE '%Lighting%'",
    limit=100000
)
# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Requirement already satisfied: pandas in c:\users\saraz\downloads\desktop\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\saraz\downloads\desktop\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Requirement already satisfied: sodapy in c:\users\saraz\downloads\desktop\lib\site-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from sodapy) (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2024.6.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
results_df
results_df.to_csv('results_df.csv',index=False)

In [28]:
results_df

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
0,24-00492200,"3103 CLYDEDALE DR, DALLAS, TX, 75220",6,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2024-10-18T23:59:00.000,Closed,2024-10-10T08:43:43.000,2024-10-10T14:10:41.000,2024-10-10T14:10:41.000,Information Provided,Standard,Phone,500cs00000CwSHzAAN,"(32.86301886251804000,-96.87223514091880000)"
1,26-00090050,"3033 PLAYA VISTA DR, DALLAS, TX, 75236",3,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-12T23:59:00.000,Closed,2026-03-05T20:23:25.000,2026-03-09T10:15:54.000,2026-03-09T10:15:35.000,Information Provided,Standard,API,500cs00001a3gn3AAA,"(32.70796314557017600,-96.89716185102122000)"
2,26-00154694,"223 EASTON RD, DALLAS, TX, 75218",9,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-04-21T23:59:00.000,Closed,2026-04-14T09:27:41.000,2026-06-18T10:25:50.000,2026-06-18T10:25:50.000,Information Provided,Standard,Phone,500cs00001htt2cAAA,"(32.86010659693609000,-96.70914302269617000)"
3,26-00087961,"2675 ANN ARBOR AVE, DALLAS, TX, 75216",4,Transportation and Public Works Department,Street Lighting- New/Relocation - TPW,10 Business Days,2026-05-28T23:59:00.000,In Progress,2026-03-04T20:03:42.000,2026-03-09T10:03:24.000,NaN,NaN,Standard,Phone,500cs00001Zo0L7AAJ,"(32.70167893239041500,-96.77770486581832000)"
4,22-00424823,"4153 MURAL LN, DALLAS, TX, 75210",7,Transportation,Street Lighting - Maintenance- TRN,5 Business Days,2022-10-12T23:59:00.000,Closed,2022-09-27T17:01:44.000,2023-06-08T02:35:39.000,2022-09-28T07:38:04.000,Information Provided,Standard,API,5008z000003geyYAAQ,"(32.76420312503126600,-96.73316692463104000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17696,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17697,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17698,20-01136860,"2248 GAYLORD DR, DALLAS, TX, 75227",5,Transportation and Public Works Department,Street Lighting- New/Relocation - TRN,10 Business Days,2021-02-17T00:59:00.000,Closed,2020-11-19T11:38:51.000,2023-06-09T03:10:50.000,2020-11-19T14:11:09.000,Information Provided,Standard,Phone,500t000000cXp33AAC,"(32.75181035147716000,-96.69054563481637000)"
17699,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"
17700,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"

In [29]:
service_light = results_df
service_light.to_csv('service_light.csv',index=False)
service_light

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
0,24-00492200,"3103 CLYDEDALE DR, DALLAS, TX, 75220",6,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2024-10-18T23:59:00.000,Closed,2024-10-10T08:43:43.000,2024-10-10T14:10:41.000,2024-10-10T14:10:41.000,Information Provided,Standard,Phone,500cs00000CwSHzAAN,"(32.86301886251804000,-96.87223514091880000)"
1,26-00090050,"3033 PLAYA VISTA DR, DALLAS, TX, 75236",3,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-12T23:59:00.000,Closed,2026-03-05T20:23:25.000,2026-03-09T10:15:54.000,2026-03-09T10:15:35.000,Information Provided,Standard,API,500cs00001a3gn3AAA,"(32.70796314557017600,-96.89716185102122000)"
2,26-00154694,"223 EASTON RD, DALLAS, TX, 75218",9,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-04-21T23:59:00.000,Closed,2026-04-14T09:27:41.000,2026-06-18T10:25:50.000,2026-06-18T10:25:50.000,Information Provided,Standard,Phone,500cs00001htt2cAAA,"(32.86010659693609000,-96.70914302269617000)"
3,26-00087961,"2675 ANN ARBOR AVE, DALLAS, TX, 75216",4,Transportation and Public Works Department,Street Lighting- New/Relocation - TPW,10 Business Days,2026-05-28T23:59:00.000,In Progress,2026-03-04T20:03:42.000,2026-03-09T10:03:24.000,NaN,NaN,Standard,Phone,500cs00001Zo0L7AAJ,"(32.70167893239041500,-96.77770486581832000)"
4,22-00424823,"4153 MURAL LN, DALLAS, TX, 75210",7,Transportation,Street Lighting - Maintenance- TRN,5 Business Days,2022-10-12T23:59:00.000,Closed,2022-09-27T17:01:44.000,2023-06-08T02:35:39.000,2022-09-28T07:38:04.000,Information Provided,Standard,API,5008z000003geyYAAQ,"(32.76420312503126600,-96.73316692463104000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17696,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17697,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17698,20-01136860,"2248 GAYLORD DR, DALLAS, TX, 75227",5,Transportation and Public Works Department,Street Lighting- New/Relocation - TRN,10 Business Days,2021-02-17T00:59:00.000,Closed,2020-11-19T11:38:51.000,2023-06-09T03:10:50.000,2020-11-19T14:11:09.000,Information Provided,Standard,Phone,500t000000cXp33AAC,"(32.75181035147716000,-96.69054563481637000)"
17699,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"
17700,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"