# 1. Light Data

In [19]:
#!/usr/bin/env python

# make sure to install these packages before running:
%pip install pandas
%pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("www.dallasopendata.com", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(www.dallasopendata.com,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
# results = client.get("d7e7-envw", limit=10000)
results = client.get(
    "d7e7-envw",
    where="service_request_type LIKE '%Lighting%'",
    limit=100000
)
# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Requirement already satisfied: pandas in c:\users\saraz\downloads\desktop\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\saraz\downloads\desktop\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Requirement already satisfied: sodapy in c:\users\saraz\downloads\desktop\lib\site-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from sodapy) (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2024.6.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
results_df
results_df.to_csv('results_df.csv',index=False)

In [21]:
results_df

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
0,26-00090050,"3033 PLAYA VISTA DR, DALLAS, TX, 75236",3,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-12T23:59:00.000,Closed,2026-03-05T20:23:25.000,2026-03-09T10:15:54.000,2026-03-09T10:15:35.000,Information Provided,Standard,API,500cs00001a3gn3AAA,"(32.70796314557017600,-96.89716185102122000)"
1,26-00087961,"2675 ANN ARBOR AVE, DALLAS, TX, 75216",4,Transportation and Public Works Department,Street Lighting- New/Relocation - TPW,10 Business Days,2026-05-28T23:59:00.000,In Progress,2026-03-04T20:03:42.000,2026-03-09T10:03:24.000,NaN,NaN,Standard,Phone,500cs00001Zo0L7AAJ,"(32.70167893239041500,-96.77770486581832000)"
2,22-00424823,"4153 MURAL LN, DALLAS, TX, 75210",7,Transportation,Street Lighting - Maintenance- TRN,5 Business Days,2022-10-12T23:59:00.000,Closed,2022-09-27T17:01:44.000,2023-06-08T02:35:39.000,2022-09-28T07:38:04.000,Information Provided,Standard,API,5008z000003geyYAAQ,"(32.76420312503126600,-96.73316692463104000)"
3,26-00091707,"1400 N WESTMORELAND RD, DALLAS, TX, 75211",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-13T23:59:00.000,Closed,2026-03-06T17:54:27.000,2026-03-09T10:21:14.000,2026-03-09T10:21:13.000,No Action Required,Standard,Phone,500cs00001aFyptAAC,"(32.76428534730311500,-96.87233482457711000)"
4,24-00492200,"3103 CLYDEDALE DR, DALLAS, TX, 75220",6,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2024-10-18T23:59:00.000,Closed,2024-10-10T08:43:43.000,2024-10-10T14:10:41.000,2024-10-10T14:10:41.000,Information Provided,Standard,Phone,500cs00000CwSHzAAN,"(32.86301886251804000,-96.87223514091880000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17696,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17697,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17698,20-01136860,"2248 GAYLORD DR, DALLAS, TX, 75227",5,Transportation and Public Works Department,Street Lighting- New/Relocation - TRN,10 Business Days,2021-02-17T00:59:00.000,Closed,2020-11-19T11:38:51.000,2023-06-09T03:10:50.000,2020-11-19T14:11:09.000,Information Provided,Standard,Phone,500t000000cXp33AAC,"(32.75181035147716000,-96.69054563481637000)"
17699,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"
17700,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"

In [24]:
service_light = results_df
service_light.to_csv('results_df.csv',index=False)
service_light

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
0,26-00090050,"3033 PLAYA VISTA DR, DALLAS, TX, 75236",3,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-12T23:59:00.000,Closed,2026-03-05T20:23:25.000,2026-03-09T10:15:54.000,2026-03-09T10:15:35.000,Information Provided,Standard,API,500cs00001a3gn3AAA,"(32.70796314557017600,-96.89716185102122000)"
1,26-00087961,"2675 ANN ARBOR AVE, DALLAS, TX, 75216",4,Transportation and Public Works Department,Street Lighting- New/Relocation - TPW,10 Business Days,2026-05-28T23:59:00.000,In Progress,2026-03-04T20:03:42.000,2026-03-09T10:03:24.000,NaN,NaN,Standard,Phone,500cs00001Zo0L7AAJ,"(32.70167893239041500,-96.77770486581832000)"
2,22-00424823,"4153 MURAL LN, DALLAS, TX, 75210",7,Transportation,Street Lighting - Maintenance- TRN,5 Business Days,2022-10-12T23:59:00.000,Closed,2022-09-27T17:01:44.000,2023-06-08T02:35:39.000,2022-09-28T07:38:04.000,Information Provided,Standard,API,5008z000003geyYAAQ,"(32.76420312503126600,-96.73316692463104000)"
3,26-00091707,"1400 N WESTMORELAND RD, DALLAS, TX, 75211",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-13T23:59:00.000,Closed,2026-03-06T17:54:27.000,2026-03-09T10:21:14.000,2026-03-09T10:21:13.000,No Action Required,Standard,Phone,500cs00001aFyptAAC,"(32.76428534730311500,-96.87233482457711000)"
4,24-00492200,"3103 CLYDEDALE DR, DALLAS, TX, 75220",6,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2024-10-18T23:59:00.000,Closed,2024-10-10T08:43:43.000,2024-10-10T14:10:41.000,2024-10-10T14:10:41.000,Information Provided,Standard,Phone,500cs00000CwSHzAAN,"(32.86301886251804000,-96.87223514091880000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17696,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17697,25-00134762,"4230 S POLK ST, DALLAS, TX, 75224",4,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-03T18:59:00.000,Closed,2025-03-27T08:42:01.000,2025-03-28T09:23:47.000,2025-03-28T09:23:31.000,Information Provided,Standard,API,500cs00000aUVUfAAO,"(32.69267869678648000,-96.83993184408519000)"
17698,20-01136860,"2248 GAYLORD DR, DALLAS, TX, 75227",5,Transportation and Public Works Department,Street Lighting- New/Relocation - TRN,10 Business Days,2021-02-17T00:59:00.000,Closed,2020-11-19T11:38:51.000,2023-06-09T03:10:50.000,2020-11-19T14:11:09.000,Information Provided,Standard,Phone,500t000000cXp33AAC,"(32.75181035147716000,-96.69054563481637000)"
17699,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"
17700,25-00507819,"1024 S TYLER ST, DALLAS, TX, 75208",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2025-10-27T23:59:00.000,Closed,2025-10-20T20:54:18.000,2025-11-14T16:58:02.000,2025-11-14T16:57:44.000,Information Provided,Standard,API,500cs000017fZh7AAE,"(32.73533252202128000,-96.83735793969156000)"

# 2. EDA

In [ ]:
traffic_signs = results_df[
    results_df["service_request_type"] == "Traffic Sign - Maintenance (Other) - TRN"
]

traffic_signs.head()

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
61,22-00275358,"THURSTON DR & EMPIRE CENTRAL, DALLAS, TX, 75235",2,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2022-07-14T23:59:00.000,Closed,2022-06-29T15:32:32.000,2023-06-08T23:24:45.000,2022-06-30T06:57:11.000,No Action Required,Standard,API,5008z000002jpAqAAI,"(32.83146180859601000,-96.84835919148941000)"
155,22-00275278,"GILFORD ST & DENTON DR, DALLAS, TX, 75235",2,Transportation and Public Works Department,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2022-07-14T23:59:00.000,Closed,2022-06-29T15:11:54.000,2023-06-08T23:24:45.000,2022-07-06T12:40:58.000,Work Completed,Standard,API,5008z000002jnuiAAA,"(32.83865980353513000,-96.85339158627497000)"
222,21-00442771,"1200 URBAN LOFTS DR, DALLAS, TX, 75215",2,Transportation and Public Works Department,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2021-06-01T23:59:00.000,Closed,2021-05-17T14:46:12.000,2023-06-09T00:56:45.000,2021-05-20T10:50:19.000,Work Completed,Standard,API,500t000000mA6A9AAK,"(32.76814763577979000,-96.79188042510144000)"
310,22-00238481,"FAWN VALLEY DR & FAWN RIDGE DR, DALLAS, TX, 75224",4,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2022-06-22T23:59:00.000,Closed,2022-06-07T15:28:43.000,2023-06-08T23:17:04.000,2022-06-09T14:05:14.000,Work Completed,Standard,Proactive,5008z000002OXFPAA4,"(32.70083385838205000,-96.83452703741956000)"
386,21-00442971,"3415 CEDAR SPRINGS RD, DALLAS, TX, 75219",14,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2021-06-01T23:59:00.000,Closed,2021-05-17T15:09:37.000,2023-06-09T00:56:47.000,2021-05-20T12:51:34.000,Work Completed,Standard,API,500t000000mA7ECAA0,"(32.80596190934913600,-96.80502526744736000)"

In [ ]:
 results_df["service_request_type"].unique()

array(['Dead Animal Pick Up - DAS', 'Water/Wastewater Line Locate - 311',
       'Code Concern - CCS', 'Barricades - Pickup/Reset/Replace - TPW',
       'Extra Police Patrol - DPD', 'Parking - Report a Violation - TPW',
       'Sanitation Roll Cart Maintenance/Delivery - SAN',
       'Building Permits Violation - DEV',
       'Street Repair - Routine - TPW', 'Traffic Signal - Flashing - TRN',
       'Narcotics/Vice Complaint - DPD', 'Street Repair - Routine - PBW',
       'Complaint/Compliment - 311',
       'Scooter/Bike Shared Dockless Vehicle - TPW',
       'Utility Cut/Routine - TPW', 'Animal Bite - DAS',
       'Alley Repair - Routine - TPW',
       'Parking - Report a Violation - TRN',
       'Lid Cover Broken - Routine - TPW',
       'Traffic Signal - Knockdown - TRN', 'Traffic Sign - New - TRN',
       'Traffic Signal - Bulb Out/NonConflict Hd Trn VO - TPW',
       'Inlet/Storm Drain Cleaning - DWU', 'Shopping Carts - PBW',
       'Sanitation Missed Recycle - SAN', 'Utility Cut/Routine - PBW',
       'Sanitation Missed Brush/Bulk - SAN',
       'Restaurant/Food Complaint - CCS',
       'Traffic Sign - Maintenance (Other) - TRN',
       'Homeless Encampment - OHS', 'Shopping Cart Routine Pickup - PBW',
       'Wheel Chair Ramp/Curb Cuts - PBW',
       'Sanitation District Billing Dispute - SAN',
       'Homeless Encampment - EMCR',
       'Single Family Rental Needs Registration - CCS',
       'Traffic - Speed Control - TRN',
       'Traffic Markings - Maintenance - TRN',
       'Traffic Signal -\xa0Visibility Obstruction\xa0- TRN',
       'Street Lighting - Maintenance- TPW',
       'Sanitation Missed Garbage - SAN',
       'Traffic Signal - Other Dispatch - TRN',
       'Alley/Sidewalk/Street Repair - Hazardous - TPW',
       'Pot Hole - Routine - TPW', 'Traffic Signal - Flashing - TPW',
       'Animal Confined - DAS', 'Pot Hole - Routine - PBW',
       'Traffic Signal - Knockdown - TPW',
       'Water/Sanitary Sewer Construction Project - DWU',
       'Animal Aggressive Behavior - DAS',
       'Chronic Noise Complaint - DPD',
       'Animal Community Cat Program - DAS',
       'Traffic Violations (Chronic) - DPD', 'Animal Loose - DAS',
       'Snow/Ice Sanding - Hazardous - PBW', 'Traffic Sign - New - TPW',
       'Traffic Signal - School Flasher Maintenance - TRN',
       'Animal Nuisance - DAS', 'Shopping Cart Routine Pickup - TPW',
       'Traffic Sign - Knockdown - TRN',
       'Construction Site Complaint - PDD',
       'Consumer Protection Complaint - CCS',
       'Street Spillage/Debris in Right of Way - Hazardous - PBW',
       'Median/Right of Way Maintenance - PBW',
       'Animal Owner Surrender - DAS', 'Clean Sweep Litter Removal - TPW',
       'Flooding - Emergency - PBW',
       'Sanitation Annual 20 Cubic Yard Exemption - SAN',
       'Traffic Signal - Bulb Out/NonConflict Hd Trn VO - TRN',
       'Tree Down/Low Limbs - PBW', 'Traffic - Construction Signs - TPW',
       'Animal Lack of Care - DAS', 'Pot Hole - Hazardous - TPW',
       'Alley/Sidewalk/Street Repair - Hazardous - PBW',
       'Sidewalk Replacement Program - PBW',
       'Traffic Signal - Other Dispatch - TPW',
       'Traffic Markings - Maintenance - TPW',
       'Mobile Food Complaint - CCS',
       'Street Lighting- New/Relocation - TPW', 'Shopping Carts - TPW',
       'Utility Complaint/Information - BMS',
       'New Street/Sidewalk/Alley - PBW',
       'Sidewalk Replacement Program - TPW',
       'Traffic - Speed Control - TPW',
       'Lid Cover Broken/Missing - Hazardous - PBW',
       'Library Concerns - LIB', 'Dead Animal Pick Up - SAN',
       'Graffiti Traffic Signal - TRN',
       'Inlet/Storm Drain Stopped Up - Hazardous - DWU',
       'Utility Cut/Hazardous - PBW', 'Railroad Crossing Repair - TPW',
       'Traffic Signal - All Out - TRN', 'Traffic Signal - Timing - TPW',
       'Street Lighting - Maintenance- TRN',
       'Median/Right of Way Maintenance - TPW',
       'Sanitation Commercial Services - SAN',
       'Sanitation Same Day Missed Collection - SAN',
       'Alley Repair - Routine - PBW', 'Traffic Signal - All Out - TPW',
       'Street/Road/Driveway Blockage - TPW',
       'Park Maintenance/Misc - PKR', 'Storm Sewer Line Locate - DWU',
       'Criminal Activities - DPD', 'Tree Down/Low Limbs - TPW',
       'Construction Right of Way/Status - PBW',
       'Pot Hole - Hazardous - PBW', 'Yard Waste - OEQS',
       'Traffic Signal - Head Turn (Conflicting) - TRN',
       'Traffic Signal - Head Turn (Conflicting) - TPW',
       '24 Hour Parking Violation - DPD',
       'Traffic Sign - Maintenance (Other) - TPW',
       'Street/Road Blockage - TPW', 'Smoke Detector Request - DFR',
       'New Street/Sidewalk/Alley - TPW', 'Animal Wildlife - DAS',
       'Visibility Obstruction - Hazardous - TPW',
       'Illegal Dumping Urgent - OEQS',
       'Miscellaneous Service Request - 311', 'Panhandling - DPD',
       'Emergency Regulations Violation - CCS', 'Water Questions - 311',
       'Boarding Home Complaint - CCS', 'Traffic Signal - New - TPW',
       'Construction Right of Way/Status - TPW',
       'Traffic Sign - Knockdown - TPW',
       'Construction Site Complaint - DEV',
       'Visibility Obstruction - TPW', 'Traffic Signal - Stuck - TRN',
       'Sewer Problems - DWU', 'Sanitation Cost-Plus - SAN',
       'Street Lighting- New/Relocation - TRN',
       'Lid Cover Broken/Missing - Hazardous - TPW',
       'Paving Street Resurface Program - TPW',
       'Lid Cover Broken - Routine - PBW',
       'Street Spillage/Debris in Right of Way - Hazardous - TPW',
       'Paving Street Resurface Program - PBW',
       'Traffic Markings - New - TRN', 'Water Main Leak/Break - DWU',
       'Traffic Signal - Stuck - TPW',
       'Sanitation Commercial Roll Cart Services - SAN',
       'Homeless Encampment - ECR',
       'ICR Consumer Protection Complaint - CCS',
       'Objects Dropped in Inlet - Hazardous - TPW',
       'Graffiti Traffic Signal - TPW',
       'Historic District Violation - PDD',
       'Drainage Ditch Cleaning/Repairs - TPW',
       'Graffiti City Streets & Bridges - PBW',
       'Building Permits Violation - SDC',
       'Building Permits Violation - PDD',
       'Storm Drainage/Flooding Complaint - DWU',
       'Sanitation Property Damage - SAN',
       'Handicap Parking Violation - DPD', 'Traffic Signal - New - TRN',
       'Utility Complaint/Information - OBS', 'Animal Loose Cat - DAS',
       '311 Event Request - 311',
       'Scooter/Bike Shared Dockless Vehicle - TRN',
       'Graffiti City Streets & Bridges - TPW',
       'Landscaping Violation (Arborist) - PDD',
       'Chemical Spill Urgent - OEQS', 'Water Pollution Urgent - DWU',
       'Traffic Sign - Visibility Obstruction - TPW',
       'Street Sweeping - Thoroughfares - PBW', 'TEST CRM',
       'Objects Dropped in Inlet - Hazardous - PBW',
       'Guardrail Repair - Hazardous - TPW',
       'City Property Management/ Real Estate - SDC',
       'Historic District Violation - OHP', 'Street/Road Blockage - TRN',
       'Animal Illegal Vending - DAS',
       'Drainage Ditch Cleaning/Repairs - PBW',
       'Creek/Culvert Maintenance -DWU', 'Steel Plates in Street - TPW',
       'Illegal Dumping Sign - CCS', 'Sanitation Helping Hands - SAN',
       'Conservation District Violation - PNV',
       'Fair Housing Complaint - OHCE',
       'Bike Lane Marking Maintenance – TRN'], dtype=object)

In [15]:
#light_df = results_df['service_request_type']
streetlights = results_df[
    results_df["service_request_type"].str.contains("Light", case=False, na=False)
]
streetlights

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
81,26-00090050,"3033 PLAYA VISTA DR, DALLAS, TX, 75236",3,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-12T23:59:00.000,Closed,2026-03-05T20:23:25.000,2026-03-09T10:15:54.000,2026-03-09T10:15:35.000,Information Provided,Standard,API,500cs00001a3gn3AAA,"(32.70796314557017600,-96.89716185102122000)"
237,26-00087961,"2675 ANN ARBOR AVE, DALLAS, TX, 75216",4,Transportation and Public Works Department,Street Lighting- New/Relocation - TPW,10 Business Days,2026-05-28T23:59:00.000,In Progress,2026-03-04T20:03:42.000,2026-03-09T10:03:24.000,NaN,NaN,Standard,Phone,500cs00001Zo0L7AAJ,"(32.70167893239041500,-96.77770486581832000)"
310,22-00424823,"4153 MURAL LN, DALLAS, TX, 75210",7,Transportation,Street Lighting - Maintenance- TRN,5 Business Days,2022-10-12T23:59:00.000,Closed,2022-09-27T17:01:44.000,2023-06-08T02:35:39.000,2022-09-28T07:38:04.000,Information Provided,Standard,API,5008z000003geyYAAQ,"(32.76420312503126600,-96.73316692463104000)"
319,26-00091707,"1400 N WESTMORELAND RD, DALLAS, TX, 75211",1,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-13T23:59:00.000,Closed,2026-03-06T17:54:27.000,2026-03-09T10:21:14.000,2026-03-09T10:21:13.000,No Action Required,Standard,Phone,500cs00001aFyptAAC,"(32.76428534730311500,-96.87233482457711000)"
355,24-00492200,"3103 CLYDEDALE DR, DALLAS, TX, 75220",6,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2024-10-18T23:59:00.000,Closed,2024-10-10T08:43:43.000,2024-10-10T14:10:41.000,2024-10-10T14:10:41.000,Information Provided,Standard,Phone,500cs00000CwSHzAAN,"(32.86301886251804000,-96.87223514091880000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9247,26-00093132,"11432 REEDER RD, DALLAS, TX, 75229",6,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-13T23:59:00.000,Closed,2026-03-08T12:45:48.000,2026-03-09T10:30:21.000,2026-03-09T10:30:20.000,Information Provided,Standard,Phone,500cs00001aRUBFAA4,"(32.89754520607693000,-96.89579904495928000)"
9502,26-00094840,"6615 LEANING OAKS ST, DALLAS, TX, 75241",8,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-16T23:59:00.000,Closed,2026-03-09T14:32:43.000,2026-03-10T09:34:59.000,2026-03-10T09:34:41.000,Information Provided,Standard,Phone,500cs00001aeUbdAAE,"(32.65605057091670000,-96.76785758965748000)"
9820,25-00149428,"1813 VIEWCREST DR, DALLAS, TX, 75228",2,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2025-04-11T18:59:00.000,Closed,2025-04-03T20:09:40.000,2025-04-04T09:56:29.000,2025-04-04T09:56:19.000,Information Provided,Standard,API,500cs00000bbPtQAAU,"(32.82102890035843500,-96.68422779863985000)"
9850,26-00090032,"8914 N CENTRAL EXPY NB, DALLAS, TX, 75231",13,Transportation and Public Works Department,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-12T23:59:00.000,Closed,2026-03-05T20:13:44.000,2026-03-10T09:36:33.000,2026-03-10T09:36:18.000,Information Provided,Standard,API,500cs00001a2p66AAA,"(32.87073305055828000,-96.76993423701776000)"
9923,26-00095643,"9470 WHITEHURST DR, DALLAS, TX, 75243",10,Transportation,Street Lighting - Maintenance- TPW,2 Business Days,2026-03-17T23:59:00.000,Closed,2026-03-10T06:35:48.000,2026-03-10T09:41:37.000,2026-03-10T09:41:37.000,Information Provided,Standard,API,500cs00001alZGQAA2,"(32.90164556560425500,-96.73420415901053000)"